/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package project_pdm;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author user
 */
public class EnrolledForm extends javax.swing.JFrame {
    private User user= User.getInstance();
    /**
     * Creates new form EnrolledForm
     */
    public EnrolledForm() throws SQLException {
        initComponents();
        txtWelcoming.setText(String.format("Welcoming %s", Student.getInstance().getStudentName()));
        createTable();
        setLocationRelativeTo(null);
        setVisible(true);
    }
    private void createTable () throws SQLException {
        SqlQuery sqlquery = new SqlQuery();
        ResultSet rs= sqlquery.getEnrolledResultSet();
        ResultSetMetaData metaData = rs.getMetaData();
        ArrayList<Object>temp = new ArrayList<>();
        int numberrows=0;
        while(rs.next())
        {
            numberrows++;
            for(int i=1;i<=metaData.getColumnCount();i++)
            {
                temp.add(rs.getObject(i));
            }
        }
        Object [][] data = new Object[numberrows][metaData.getColumnCount()];
        for(int i=0;i<numberrows;i++)
        {
            for(int j=0;j<metaData.getColumnCount();j++)
            {
                data[i][j]= temp.get(0);
                temp.remove(0);
            }
        }
        String[] column = new String[metaData.getColumnCount()];
        for(int i=0;i<metaData.getColumnCount();i++)    column[i]= metaData.getColumnName(i+1);
        showtable.setModel(new DefaultTableModel(
                data,
                column
        ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        btnAddingCourse = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtWelcoming = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        showtable = new javax.swing.JTable();
        btnLogout1 = new javax.swing.JButton();
        btnDeleteCourse = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Enrolled-Icon.png"))); // NOI18N
        jLabel2.setText("ENROLLED COURSE");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 409, -1));

        btnAddingCourse.setBackground(new java.awt.Color(204, 204, 204));
        btnAddingCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Add-icon-64.png"))); // NOI18N
        btnAddingCourse.setText("Adding course");
        btnAddingCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddingCourseActionPerformed(evt);
            }
        });
        getContentPane().add(btnAddingCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 230, 190, 60));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/10207-man-student-light-skin-tone-icon-64.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, -1, -1));

        txtWelcoming.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtWelcoming.setText("jLabel4");
        getContentPane().add(txtWelcoming, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 220, -1, -1));

        showtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(showtable);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 867, 339));

        btnLogout1.setBackground(new java.awt.Color(204, 204, 204));
        btnLogout1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/LogoutEnrolled-icon.png"))); // NOI18N
        btnLogout1.setText("Main Page");
        btnLogout1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogout1ActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 0, -1, -1));

        btnDeleteCourse.setBackground(new java.awt.Color(204, 204, 204));
        btnDeleteCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Actions-edit-delete-icon-48.png"))); // NOI18N
        btnDeleteCourse.setText("Deleting course");
        btnDeleteCourse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteCourseActionPerformed(evt);
            }
        });
        getContentPane().add(btnDeleteCourse, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 230, 180, 60));

        jLabel5.setBackground(new java.awt.Color(204, 255, 204));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/EnrolledBackground3.png"))); // NOI18N
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 360, -1, 180));

        jLabel4.setBackground(new java.awt.Color(255, 204, 204));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/EnrolledBackground2.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 940, 180));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/EnrolledBackground1.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 920, 190));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 410, 37, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/EnrolledBackground4.png"))); // NOI18N
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 540, 940, 150));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/EnrolledBackground1.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 0, 270, 190));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/EnrolledBackground2.png"))); // NOI18N
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 190, 270, 170));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/EnrolledBackground3.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 360, 180, 180));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/EnrolledBackground4.png"))); // NOI18N
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 270, 150));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddingCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddingCourseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        try {
            new AddingCourseForm();
        } catch (SQLException ex) {
            Logger.getLogger(EnrolledForm.class.getName()).log(Level.SEVERE, null, ex);
        }
         

    }//GEN-LAST:event_btnAddingCourseActionPerformed

    private void btnLogout1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogout1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new MainFrom();
    }//GEN-LAST:event_btnLogout1ActionPerformed

    private void btnDeleteCourseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteCourseActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        try {
            new DeletingCourseForm();
        } catch (SQLException ex) {
            Logger.getLogger(EnrolledForm.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDeleteCourseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EnrolledForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EnrolledForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EnrolledForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EnrolledForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new EnrolledForm().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(EnrolledForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddingCourse;
    private javax.swing.JButton btnDeleteCourse;
    private javax.swing.JButton btnLogout1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable showtable;
    private javax.swing.JLabel txtWelcoming;
    // End of variables declaration//GEN-END:variables
}
