/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
//package project_pdm;

/**
 *
 * @author user
 */

package  project_pdm;
import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import org.xml.sax.Attributes;




public class MainFrom extends javax.swing.JFrame {

    
    /**
     * Creates new form MainFrom
     */
    public MainFrom() {
        setVisible(true);
        initComponents();
        setLocationRelativeTo(null);
        txtWelcoming.setText(String.format("Welcoming %s", Student.getInstance().getStudentName()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLogout = new javax.swing.JButton();
        btnEnrolled = new javax.swing.JButton();
        btnFee = new javax.swing.JButton();
        btnGrade = new javax.swing.JButton();
        btnInformation = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtWelcoming = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/LogoutEnrolled-icon.png"))); // NOI18N
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 0, -1, -1));

        btnEnrolled.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/edit-icon-64.png"))); // NOI18N
        btnEnrolled.setText("Enrolled");
        btnEnrolled.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnrolledActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnrolled, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 300, 209, 85));

        btnFee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/money.png"))); // NOI18N
        btnFee.setText("Fee");
        btnFee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFeeActionPerformed(evt);
            }
        });
        getContentPane().add(btnFee, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 460, 209, -1));

        btnGrade.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/score-icon.png"))); // NOI18N
        btnGrade.setText("Grade");
        btnGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGradeActionPerformed(evt);
            }
        });
        getContentPane().add(btnGrade, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 209, 89));

        btnInformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Personal-information.png"))); // NOI18N
        btnInformation.setText("Personal information");
        btnInformation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInformationActionPerformed(evt);
            }
        });
        getContentPane().add(btnInformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 460, 209, 81));

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel2.setText("STUDENT SAVING RECORDS");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 170, 550, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/10207-man-student-light-skin-tone-icon-64.png"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        txtWelcoming.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        txtWelcoming.setText("jLabel4");
        getContentPane().add(txtWelcoming, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/BackgroundMainForm.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1200, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        User.getInstance().setadmin(false);
        new LoginForm();
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnEnrolledActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnrolledActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        try {
            new EnrolledForm();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnEnrolledActionPerformed

    private void btnInformationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInformationActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        try {
            new PersonalInformation();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnInformationActionPerformed

    private void btnFeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFeeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        try {
            new Feeform();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnFeeActionPerformed

    private void btnGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGradeActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        try {
            new GradeForm();
        } catch (SQLException ex) {
            Logger.getLogger(MainFrom.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGradeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEnrolled;
    private javax.swing.JButton btnFee;
    private javax.swing.JButton btnGrade;
    private javax.swing.JButton btnInformation;
    private javax.swing.JButton btnLogout;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel txtWelcoming;
    // End of variables declaration//GEN-END:variables
}
