/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ASUS
 */
package  project_pdm;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class PersonalInformation extends javax.swing.JFrame {

    private Student student= Student.getInstance();
    /**
     * Creates new form PersonalInformation
     */
    public PersonalInformation() throws SQLException {
        initComponents();
        setLocationRelativeTo(null);
        labelStudentID.setText(String.format("MSSV: %s", Student.getInstance().getStudentID()));
        labelStudentName.setText(String.format("MSSV: %s", Student.getInstance().getStudentName()));
        labelGender.setText(String.format("MSSV: %s", Student.getInstance().getGender()));
        SqlQuery sqlquery = new SqlQuery();
        ResultSet rs= sqlquery.getMajorResultSet();
        String major=null;
        while(rs.next())
        {
            major=(String)rs.getObject(1);
            break;
        }
        
        labelMajor.setText(String.format("Major: %s",major));
        System.out.println("20" + Integer.parseInt(Student.getInstance().getDob().substring(7, 9))+4);
        //labelGraduatedYear.setText(String.valueOf(Student.getInstance().getBirthYear()+18));
        setVisible(true);
       
    }
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        labelStudentID = new javax.swing.JLabel();
        labelStudentName = new javax.swing.JLabel();
        labelMajor = new javax.swing.JLabel();
        labelGender = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Cloud-icon.png"))); // NOI18N

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Cloud-icon.png"))); // NOI18N

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Cloud-icon.png"))); // NOI18N

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 255, 204));

        jLabel1.setBackground(new java.awt.Color(51, 255, 153));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/IU1-icon.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(51, 255, 153));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Cloud-icon.png"))); // NOI18N

        jLabel3.setBackground(new java.awt.Color(51, 255, 153));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Cloud-icon.png"))); // NOI18N

        jLabel4.setBackground(new java.awt.Color(51, 255, 153));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Cloud-icon.png"))); // NOI18N

        jLabel5.setBackground(new java.awt.Color(51, 255, 153));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Cloud-icon.png"))); // NOI18N

        jLabel6.setBackground(new java.awt.Color(51, 255, 153));
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Cloud-icon.png"))); // NOI18N

        jLabel7.setBackground(new java.awt.Color(51, 255, 153));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Cloud-icon.png"))); // NOI18N

        jLabel8.setBackground(new java.awt.Color(51, 255, 153));
        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Cloud-icon.png"))); // NOI18N

        jLabel11.setBackground(new java.awt.Color(51, 255, 153));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Cloud-icon.png"))); // NOI18N

        jLabel13.setBackground(new java.awt.Color(51, 255, 153));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Cloud-icon.png"))); // NOI18N

        jLabel14.setBackground(new java.awt.Color(51, 255, 153));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Tree-icon.png"))); // NOI18N

        jLabel15.setBackground(new java.awt.Color(51, 255, 153));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Tree-icon.png"))); // NOI18N

        jLabel16.setBackground(new java.awt.Color(51, 255, 153));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Student-icon.png"))); // NOI18N
        jLabel16.setText("jLabel16");

        labelStudentID.setBackground(new java.awt.Color(51, 255, 153));
        labelStudentID.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        labelStudentID.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Identified-icon.png"))); // NOI18N
        labelStudentID.setText("Mssv: ");
        labelStudentID.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelStudentName.setBackground(new java.awt.Color(51, 255, 153));
        labelStudentName.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        labelStudentName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Name-icon.png"))); // NOI18N
        labelStudentName.setText("Tên: Nguyen Trong Nghia");
        labelStudentName.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelMajor.setBackground(new java.awt.Color(51, 255, 153));
        labelMajor.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        labelMajor.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Curriculum-icon.png"))); // NOI18N
        labelMajor.setText("Curriculum: Information Technology");
        labelMajor.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        labelGender.setBackground(new java.awt.Color(51, 255, 153));
        labelGender.setFont(new java.awt.Font("Segoe UI Semibold", 3, 18)); // NOI18N
        labelGender.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Gender-icon.png"))); // NOI18N
        labelGender.setText("Gender: Male");
        labelGender.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);

        jButton1.setBackground(new java.awt.Color(51, 255, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Data/Back-icon.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(89, 89, 89))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel7)
                                .addGap(51, 51, 51)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(154, 154, 154)
                                        .addComponent(jLabel11))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(21, 21, 21)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel4)
                                                .addGap(327, 327, 327))
                                            .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(8, 8, 8)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(labelStudentName)
                                            .addComponent(labelStudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)))
                        .addComponent(jLabel8)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)
                        .addGap(24, 24, 24))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(27, 27, 27)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(227, 227, 227)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(344, 344, 344)
                    .addComponent(jLabel13)
                    .addContainerGap(492, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jLabel5)
                                .addGap(2, 2, 2)
                                .addComponent(jLabel3))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(47, 47, 47)
                                            .addComponent(jLabel4))
                                        .addComponent(jLabel1))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addGap(47, 47, 47)
                                        .addComponent(jLabel7)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel16)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(0, 17, Short.MAX_VALUE)
                                        .addComponent(labelStudentID)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(labelStudentName))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel8)
                        .addGap(70, 70, 70)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 184, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelGender, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19)
                        .addComponent(labelMajor, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)
                        .addGap(67, 67, 67))))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(90, 90, 90)
                    .addComponent(jLabel13)
                    .addContainerGap(571, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        new MainFrom();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalInformation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new PersonalInformation().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(PersonalInformation.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel labelGender;
    private javax.swing.JLabel labelMajor;
    private javax.swing.JLabel labelStudentID;
    private javax.swing.JLabel labelStudentName;
    // End of variables declaration//GEN-END:variables
}
